---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - name: tetris
<<<<<<< HEAD
        image: freelancerdev/tetrisv1:14    # <------------------ change this
=======
        image: freelancerdev/tetrisv2:1
>>>>>>> 0f1a905607d4920e1ce6c59bf8a6ce81250fa12d
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tetris-service
spec:
  selector:
    app: tetris
  ports:
  - protocol: TCP
    port: 80                
    targetPort: 3000
  type: LoadBalancer
